name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  tests:
    # Will not run if the event is a PR to bump-meilisearch-v* (so a pre-release PR)
    # Will still run for each push to bump-meilisearch-v*
    if: github.event_name != 'pull_request' || !startsWith(github.base_ref, 'bump-meilisearch-v')
    name: build-image-test
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      REQUEST_TIMEOUT_ENV_VAR: "30"
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Set image name as env variable
      run: echo "IMAGE_NAME=meilisearch_digitalocean_ci_test_$(date +'%d-%m-%Y-%H-%M-%S')" >> $GITHUB_ENV
    - name: Build image
      run: python3 tools/build_image.py $IMAGE_NAME
    - name: Test image
      run: python3 tools/test_image.py $IMAGE_NAME
    - name: Clean image
      if: ${{ always() }}
      run: python3 tools/destroy_image.py $IMAGE_NAME
    
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Linter with pylint
        run: pylint tools
